// Codegen: extract just the game-icons (https://game-icons.net) we actually use
// out of the full @iconify-json/game-icons collection (~4000 icons, ~6 MB) into a
// small typed module the app imports. Keeps the client bundle to the handful of
// badge/award/level icons listed in lib/icons/used.json instead of the whole set.
//
// Run: `npm run build:icons` (also wired into prebuild). Re-run after editing
// used.json. Errors loudly if any listed name doesn't exist in the collection.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const collection = require("@iconify-json/game-icons/icons.json");

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const usedPath = join(root, "lib/icons/used.json");
const outPath = join(root, "lib/icons/data.generated.ts");

const { icons: names } = JSON.parse(readFileSync(usedPath, "utf8"));
const W = collection.width ?? 512;
const H = collection.height ?? 512;

const missing = names.filter((n) => !collection.icons[n]);
if (missing.length) {
  console.error(`build-icons: ${missing.length} name(s) not in game-icons:\n  ${missing.join("\n  ")}`);
  process.exit(1);
}

const entries = [...new Set(names)].sort().map((name) => {
  const ic = collection.icons[name];
  // Iconify bodies use fill="currentColor"; keep them verbatim so both inline-SVG
  // (CSS color) and canvas (string-replace currentColor) can tint them.
  const body = JSON.stringify(ic.body);
  const w = ic.width ?? W;
  const h = ic.height ?? H;
  return `  ${JSON.stringify(name)}: { body: ${body}, w: ${w}, h: ${h} },`;
});

const out = `// GENERATED by scripts/build-icons.mjs from @iconify-json/game-icons.
// Do not edit by hand. Add names to lib/icons/used.json and run \`npm run build:icons\`.
// Icons: game-icons.net, CC BY 3.0 (see lib/icons/index.ts for attribution).

export interface IconData {
  body: string; // raw SVG inner markup, fill="currentColor"
  w: number;
  h: number;
}

export const ICONS: Record<string, IconData> = {
${entries.join("\n")}
};
`;

writeFileSync(outPath, out);
console.log(`build-icons: wrote ${entries.length} icons → ${outPath.replace(root + "\\", "").replace(root + "/", "")}`);
